// Copyright (C) 2015-2025 The Neo Project.
// Licensed under the MIT License.

using FluentAssertions;
using Neo.Fairy.Core.CodeGen;
using Xunit;

namespace Neo.Fairy.Core.Tests.CodeGen;

public class ContractInterfaceGeneratorTests
{
    private const string CounterManifest = """
    {
        "name": "Counter",
        "groups": [],
        "supportedstandards": [],
        "abi": {
            "methods": [
                {
                    "name": "getCount",
                    "parameters": [],
                    "returntype": "Integer",
                    "offset": 0,
                    "safe": true
                },
                {
                    "name": "increment",
                    "parameters": [],
                    "returntype": "Void",
                    "offset": 100,
                    "safe": false
                },
                {
                    "name": "decrement",
                    "parameters": [],
                    "returntype": "Void",
                    "offset": 200,
                    "safe": false
                },
                {
                    "name": "setCount",
                    "parameters": [
                        { "name": "value", "type": "Integer" }
                    ],
                    "returntype": "Void",
                    "offset": 300,
                    "safe": false
                },
                {
                    "name": "_deploy",
                    "parameters": [
                        { "name": "data", "type": "Any" },
                        { "name": "update", "type": "Boolean" }
                    ],
                    "returntype": "Void",
                    "offset": 400,
                    "safe": false
                }
            ],
            "events": [
                {
                    "name": "CountChanged",
                    "parameters": [
                        { "name": "oldValue", "type": "Integer" },
                        { "name": "newValue", "type": "Integer" }
                    ]
                }
            ]
        },
        "permissions": [],
        "trusts": []
    }
    """;

    [Fact]
    public void Generate_ReturnsGeneratedCode()
    {
        // Arrange
        var generator = new ContractInterfaceGenerator();

        // Act
        var result = generator.Generate(CounterManifest);

        // Assert
        result.Should().NotBeNull();
        result.FileName.Should().Be("Counter.g.cs");
        result.ContractName.Should().Be("Counter");
        result.ClassName.Should().Be("Counter");
        result.Content.Should().NotBeNullOrEmpty();
    }

    [Fact]
    public void Generate_WithAlias_UsesAliasForClassName()
    {
        // Arrange
        var generator = new ContractInterfaceGenerator();

        // Act
        var result = generator.Generate(CounterManifest, "my_counter");

        // Assert
        result.ClassName.Should().Be("MyCounter");
        result.FileName.Should().Be("MyCounter.g.cs");
    }

    [Fact]
    public void Generate_ContainsAutoGeneratedHeader()
    {
        // Arrange
        var generator = new ContractInterfaceGenerator();

        // Act
        var result = generator.Generate(CounterManifest);

        // Assert
        result.Content.Should().Contain("<auto-generated>");
        result.Content.Should().Contain("Neo Fairy Framework");
    }

    [Fact]
    public void Generate_ContainsInterface()
    {
        // Arrange
        var generator = new ContractInterfaceGenerator();

        // Act
        var result = generator.Generate(CounterManifest);

        // Assert
        result.Content.Should().Contain("public interface ICounter");
    }

    [Fact]
    public void Generate_ContainsWrapperClass()
    {
        // Arrange
        var generator = new ContractInterfaceGenerator();

        // Act
        var result = generator.Generate(CounterManifest);

        // Assert
        result.Content.Should().Contain("public sealed class Counter : ICounter");
    }

    [Fact]
    public void Generate_InterfaceContainsMethods()
    {
        // Arrange
        var generator = new ContractInterfaceGenerator();

        // Act
        var result = generator.Generate(CounterManifest);

        // Assert
        result.Content.Should().Contain("BigInteger GetCount()");
        result.Content.Should().Contain("void Increment()");
        result.Content.Should().Contain("void Decrement()");
        result.Content.Should().Contain("void SetCount(BigInteger value)");
    }

    [Fact]
    public void Generate_ExcludesInternalMethods()
    {
        // Arrange
        var generator = new ContractInterfaceGenerator();

        // Act
        var result = generator.Generate(CounterManifest);

        // Assert
        // _deploy should not appear in interface or wrapper
        result.Content.Should().NotContain("void Deploy(");
        result.Content.Should().NotContain("\"_deploy\"");
    }

    [Fact]
    public void Generate_WrapperHasConstructor()
    {
        // Arrange
        var generator = new ContractInterfaceGenerator();

        // Act
        var result = generator.Generate(CounterManifest);

        // Assert
        result.Content.Should().Contain("public Counter(IContractInvoker invoker, string contractHash)");
    }

    [Fact]
    public void Generate_WrapperHasContractHashProperty()
    {
        // Arrange
        var generator = new ContractInterfaceGenerator();

        // Act
        var result = generator.Generate(CounterManifest);

        // Assert
        result.Content.Should().Contain("public string ContractHash => _contractHash");
    }

    [Fact]
    public void Generate_WrapperMethodsCallInvoker()
    {
        // Arrange
        var generator = new ContractInterfaceGenerator();

        // Act
        var result = generator.Generate(CounterManifest);

        // Assert
        result.Content.Should().Contain("_invoker.Call<BigInteger>(_contractHash, \"getCount\")");
        result.Content.Should().Contain("_invoker.Call(_contractHash, \"increment\")");
    }

    [Fact]
    public void Generate_ContainsEventClasses()
    {
        // Arrange
        var generator = new ContractInterfaceGenerator();

        // Act
        var result = generator.Generate(CounterManifest);

        // Assert
        result.Content.Should().Contain("public static class CounterEvents");
        result.Content.Should().Contain("public sealed class CountChangedEvent");
        result.Content.Should().Contain("public const string EventName = \"CountChanged\"");
    }

    [Fact]
    public void Generate_EventClassHasProperties()
    {
        // Arrange
        var generator = new ContractInterfaceGenerator();

        // Act
        var result = generator.Generate(CounterManifest);

        // Assert
        result.Content.Should().Contain("public BigInteger OldValue { get; init; }");
        result.Content.Should().Contain("public BigInteger NewValue { get; init; }");
    }

    [Fact]
    public void Generate_WithCustomNamespace_UsesNamespace()
    {
        // Arrange
        var generator = new ContractInterfaceGenerator(new GeneratorOptions
        {
            Namespace = "MyProject.Contracts"
        });

        // Act
        var result = generator.Generate(CounterManifest);

        // Assert
        result.Content.Should().Contain("namespace MyProject.Contracts;");
    }

    [Fact]
    public void Generate_ContainsRequiredUsings()
    {
        // Arrange
        var generator = new ContractInterfaceGenerator();

        // Act
        var result = generator.Generate(CounterManifest);

        // Assert
        result.Content.Should().Contain("using System.Numerics;");
        result.Content.Should().Contain("using Neo.Fairy.Core.Models;");
    }

    [Fact]
    public void Generate_HasCallRawMethod()
    {
        // Arrange
        var generator = new ContractInterfaceGenerator();

        // Act
        var result = generator.Generate(CounterManifest);

        // Assert
        result.Content.Should().Contain("public ExecutionResult CallRaw(string method, params object[] args)");
    }

    [Fact]
    public void Generate_MethodWithParameters_GeneratesCorrectSignature()
    {
        // Arrange
        var manifest = """
        {
            "name": "Token",
            "groups": [],
            "supportedstandards": [],
            "abi": {
                "methods": [
                    {
                        "name": "transfer",
                        "parameters": [
                            { "name": "from", "type": "Hash160" },
                            { "name": "to", "type": "Hash160" },
                            { "name": "amount", "type": "Integer" }
                        ],
                        "returntype": "Boolean",
                        "offset": 0,
                        "safe": false
                    }
                ],
                "events": []
            },
            "permissions": [],
            "trusts": []
        }
        """;
        var generator = new ContractInterfaceGenerator();

        // Act
        var result = generator.Generate(manifest);

        // Assert
        result.Content.Should().Contain("bool Transfer(string? from, string? to, BigInteger amount)");
        result.Content.Should().Contain("_invoker.Call<bool>(_contractHash, \"transfer\", from, to, amount)");
    }

    [Fact]
    public void Generate_PascalCaseConversion_WorksCorrectly()
    {
        // Arrange
        var manifest = """
        {
            "name": "my_test_contract",
            "groups": [],
            "supportedstandards": [],
            "abi": {
                "methods": [
                    {
                        "name": "get_balance",
                        "parameters": [],
                        "returntype": "Integer",
                        "offset": 0,
                        "safe": true
                    }
                ],
                "events": []
            },
            "permissions": [],
            "trusts": []
        }
        """;
        var generator = new ContractInterfaceGenerator();

        // Act
        var result = generator.Generate(manifest);

        // Assert
        result.ClassName.Should().Be("MyTestContract");
        result.Content.Should().Contain("BigInteger GetBalance()");
    }
}
