<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Neo.Fairy.Core</RootNamespace>
    <AssemblyName>Neo.Fairy.Core</AssemblyName>
    <Version>1.2.0</Version>
    <Authors>Neo Project</Authors>
    <Description>Core abstractions and models for Neo Fairy Framework</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Tomlyn" Version="0.19.0" />
    <PackageReference Include="Neo" Version="3.9.1" />
  </ItemGroup>

</Project>
