// Copyright (C) 2015-2025 The Neo Project.
// Licensed under the MIT License.

using System.Text;
using Neo.Fairy.Core.Models;

namespace Neo.Fairy.Core.CodeGen;

/// <summary>
/// Generates C# interface and wrapper classes for Neo smart contracts.
/// Similar to Foundry's contract bindings generation.
/// </summary>
public sealed class ContractInterfaceGenerator
{
    private readonly GeneratorOptions _options;

    public ContractInterfaceGenerator(GeneratorOptions? options = null)
    {
        _options = options ?? new GeneratorOptions();
    }

    /// <summary>
    /// Generates C# code for a contract interface from manifest.
    /// </summary>
    public GeneratedCode Generate(string manifestJson, string? contractAlias = null)
    {
        var manifest = ManifestParser.Parse(manifestJson);
        var className = ToPascalCase(contractAlias ?? manifest.Name);

        var sb = new StringBuilder();

        // File header
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This code was generated by Neo Fairy Framework.");
        sb.AppendLine("// Do not modify this file manually.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // Usings
        sb.AppendLine("using Neo.Fairy.Core.Models;");
        sb.AppendLine("using Neo.Fairy.Testing;");
        sb.AppendLine("using System.Numerics;");
        sb.AppendLine();

        // Namespace
        sb.AppendLine($"namespace {_options.Namespace};");
        sb.AppendLine();

        // Generate interface
        GenerateInterface(sb, manifest, className);
        sb.AppendLine();

        // Generate wrapper class
        GenerateWrapperClass(sb, manifest, className);
        sb.AppendLine();

        // Generate event classes
        GenerateEventClasses(sb, manifest, className);

        return new GeneratedCode
        {
            FileName = $"{className}.g.cs",
            Content = sb.ToString(),
            ContractName = manifest.Name,
            ClassName = className
        };
    }

    private void GenerateInterface(StringBuilder sb, ContractManifest manifest, string className)
    {
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Interface for {manifest.Name} contract.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public interface I{className}");
        sb.AppendLine("{");

        foreach (var method in manifest.Abi.Methods.Where(m => !m.IsInternal))
        {
            var returnType = MapReturnType(method.ReturnType);
            var methodName = ToSafeMethodName(method.Name);
            var parameters = GenerateParameters(method.Parameters);

            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Calls the {method.Name} method.");
            if (method.Safe)
                sb.AppendLine($"    /// This is a safe (read-only) method.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    {returnType} {methodName}({parameters});");
            sb.AppendLine();
        }

        sb.AppendLine("}");
    }

    private void GenerateWrapperClass(StringBuilder sb, ContractManifest manifest, string className)
    {
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Wrapper class for {manifest.Name} contract invocation.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public sealed class {className} : I{className}");
        sb.AppendLine("{");

        // Fields
        sb.AppendLine("    private readonly IContractInvoker _invoker;");
        sb.AppendLine("    private readonly string _contractHash;");
        sb.AppendLine();

        // Contract hash property
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gets the contract hash.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public string ContractHash => _contractHash;");
        sb.AppendLine();

        // Constructor
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// Creates a new {className} wrapper.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"invoker\">The contract invoker.</param>");
        sb.AppendLine("    /// <param name=\"contractHash\">The deployed contract hash.</param>");
        sb.AppendLine($"    public {className}(IContractInvoker invoker, string contractHash)");
        sb.AppendLine("    {");
        sb.AppendLine("        _invoker = invoker;");
        sb.AppendLine("        _contractHash = contractHash;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Generate methods
        foreach (var method in manifest.Abi.Methods.Where(m => !m.IsInternal))
        {
            GenerateMethod(sb, method);
        }

        // Generate raw call method
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Invokes a method and returns the raw execution result.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public ExecutionResult CallRaw(string method, params object[] args)");
        sb.AppendLine("    {");
        sb.AppendLine("        return _invoker.Call(_contractHash, method, args);");
        sb.AppendLine("    }");

        sb.AppendLine("}");
    }

    private void GenerateMethod(StringBuilder sb, ContractMethod method)
    {
        var returnType = MapReturnType(method.ReturnType);
        var methodName = ToSafeMethodName(method.Name);
        var parameters = GenerateParameters(method.Parameters);
        var argsList = GenerateArgumentsList(method.Parameters);

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Calls the {method.Name} method.");
        sb.AppendLine($"    /// </summary>");

        foreach (var param in method.Parameters)
        {
            sb.AppendLine($"    /// <param name=\"{ToSafeParameterName(param.Name)}\">{param.Name} parameter.</param>");
        }

        if (method.ReturnType != ContractParameterType.Void)
        {
            sb.AppendLine($"    /// <returns>The method result.</returns>");
        }

        sb.AppendLine($"    public {returnType} {methodName}({parameters})");
        sb.AppendLine("    {");

        if (method.ReturnType == ContractParameterType.Void)
        {
            sb.AppendLine($"        _invoker.Call(_contractHash, \"{method.Name}\"{argsList});");
        }
        else
        {
            var genericType = MapGenericType(method.ReturnType);
            sb.AppendLine($"        return _invoker.Call<{genericType}>(_contractHash, \"{method.Name}\"{argsList});");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private void GenerateEventClasses(StringBuilder sb, ContractManifest manifest, string className)
    {
        if (manifest.Abi.Events.Count == 0) return;

        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Event classes for {manifest.Name} contract.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public static class {className}Events");
        sb.AppendLine("{");

        foreach (var evt in manifest.Abi.Events)
        {
            var eventClassName = ToPascalCase(evt.Name) + "Event";

            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// Represents the {evt.Name} event.");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public sealed class {eventClassName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        public const string EventName = \"{evt.Name}\";");
            sb.AppendLine();

            foreach (var param in evt.Parameters)
            {
                var propType = MapPropertyType(param.Type);
                var propName = ToPascalCase(param.Name);
                sb.AppendLine($"        public {propType} {propName} {{ get; init; }}");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
    }

    private string GenerateParameters(List<ContractParameter> parameters)
    {
        if (parameters.Count == 0) return "";

        return string.Join(", ", parameters.Select(p =>
            $"{MapPropertyType(p.Type)} {ToSafeParameterName(p.Name)}"));
    }

    private string GenerateArgumentsList(List<ContractParameter> parameters)
    {
        if (parameters.Count == 0) return "";

        var args = string.Join(", ", parameters.Select(p => ToSafeParameterName(p.Name)));
        return $", {args}";
    }

    private static string MapReturnType(ContractParameterType type)
    {
        return type switch
        {
            ContractParameterType.Void => "void",
            ContractParameterType.Boolean => "bool",
            ContractParameterType.Integer => "BigInteger",
            ContractParameterType.ByteArray => "byte[]",
            ContractParameterType.String => "string",
            ContractParameterType.Hash160 => "string",
            ContractParameterType.Hash256 => "string",
            ContractParameterType.PublicKey => "string",
            ContractParameterType.Array => "object[]",
            ContractParameterType.Map => "IDictionary<object, object>",
            _ => "object?"
        };
    }

    private static string MapGenericType(ContractParameterType type)
    {
        return type switch
        {
            ContractParameterType.Boolean => "bool",
            ContractParameterType.Integer => "BigInteger",
            ContractParameterType.ByteArray => "byte[]",
            ContractParameterType.String => "string",
            ContractParameterType.Hash160 => "string",
            ContractParameterType.Hash256 => "string",
            ContractParameterType.PublicKey => "string",
            ContractParameterType.Array => "object[]",
            ContractParameterType.Map => "IDictionary<object, object>",
            _ => "object"
        };
    }

    private static string MapPropertyType(ContractParameterType type)
    {
        return type switch
        {
            ContractParameterType.Boolean => "bool",
            ContractParameterType.Integer => "BigInteger",
            ContractParameterType.ByteArray => "byte[]?",
            ContractParameterType.String => "string?",
            ContractParameterType.Hash160 => "string?",
            ContractParameterType.Hash256 => "string?",
            ContractParameterType.PublicKey => "string?",
            ContractParameterType.Array => "object[]?",
            ContractParameterType.Map => "IDictionary<object, object>?",
            _ => "object?"
        };
    }

    // C# reserved keywords that need escaping with @
    private static readonly HashSet<string> CSharpKeywords = new(StringComparer.OrdinalIgnoreCase)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char",
        "checked", "class", "const", "continue", "decimal", "default", "delegate",
        "do", "double", "else", "enum", "event", "explicit", "extern", "false",
        "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit",
        "in", "int", "interface", "internal", "is", "lock", "long", "namespace",
        "new", "null", "object", "operator", "out", "override", "params", "private",
        "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
        "short", "sizeof", "stackalloc", "static", "string", "struct", "switch",
        "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked",
        "unsafe", "ushort", "using", "virtual", "void", "volatile", "while"
    };

    private static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;

        var sb = new StringBuilder();
        var capitalizeNext = true;

        foreach (var c in name)
        {
            if (c == '_' || c == '-' || c == ' ')
            {
                capitalizeNext = true;
                continue;
            }

            if (capitalizeNext)
            {
                sb.Append(char.ToUpperInvariant(c));
                capitalizeNext = false;
            }
            else
            {
                sb.Append(c);
            }
        }

        return sb.ToString();
    }

    private static string ToCamelCase(string name)
    {
        var pascal = ToPascalCase(name);
        if (string.IsNullOrEmpty(pascal)) return pascal;
        return char.ToLowerInvariant(pascal[0]) + pascal[1..];
    }

    /// <summary>
    /// Converts a name to a safe C# method name, escaping keywords with @.
    /// </summary>
    private static string ToSafeMethodName(string name)
    {
        var pascal = ToPascalCase(name);
        return CSharpKeywords.Contains(pascal) ? $"@{pascal}" : pascal;
    }

    /// <summary>
    /// Converts a name to a safe C# parameter name, escaping keywords with @.
    /// </summary>
    private static string ToSafeParameterName(string name)
    {
        var camel = ToCamelCase(name);
        return CSharpKeywords.Contains(camel) ? $"@{camel}" : camel;
    }
}

/// <summary>
/// Options for code generation.
/// </summary>
public sealed class GeneratorOptions
{
    /// <summary>
    /// Gets or sets the namespace for generated code.
    /// </summary>
    public string Namespace { get; set; } = "Neo.Fairy.Generated";

    /// <summary>
    /// Gets or sets whether to generate async methods.
    /// </summary>
    public bool GenerateAsync { get; set; } = false;

    /// <summary>
    /// Gets or sets whether to generate XML documentation.
    /// </summary>
    public bool GenerateDocumentation { get; set; } = true;
}

/// <summary>
/// Result of code generation.
/// </summary>
public sealed class GeneratedCode
{
    /// <summary>
    /// Gets the generated file name.
    /// </summary>
    public required string FileName { get; init; }

    /// <summary>
    /// Gets the generated code content.
    /// </summary>
    public required string Content { get; init; }

    /// <summary>
    /// Gets the original contract name.
    /// </summary>
    public required string ContractName { get; init; }

    /// <summary>
    /// Gets the generated class name.
    /// </summary>
    public required string ClassName { get; init; }
}

/// <summary>
/// Interface for contract invocation.
/// Implemented by FairyTest and other test/deployment tools.
/// </summary>
public interface IContractInvoker
{
    /// <summary>
    /// Invokes a contract method.
    /// </summary>
    ExecutionResult Call(string contractHash, string method, params object[] args);

    /// <summary>
    /// Invokes a contract method and returns a typed result.
    /// </summary>
    T? Call<T>(string contractHash, string method, params object[] args);
}
